In [1]:
#import all the required libraries
import pandas as pd
import selenium
from selenium import webdriver
import time
from selenium.common.exceptions import StaleElementReferenceException, NoSuchElementException

In [3]:
#opening the link

driver=webdriver.Chrome("chromedriver.exe") 
time.sleep(4)

url = "https://timesofindia.indiatimes.com/archive/year-2018,month-4.cms"
driver.get(url)
time.sleep(6)

In [4]:
#https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42615.cms
archive_url = []
i=1
k = 42614
while i <31:
    
    archive_url.append('https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-'+str(k)+'.cms')
    i = i+1
    k=k+1
archive_url

['https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42614.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42615.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42616.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42617.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42618.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42619.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42620.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42621.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42622.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42623.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42624.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42625.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42626.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42627.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42628.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42629.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42630.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42631.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42632.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42633.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42634.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42635.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42636.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42637.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42638.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42639.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42640.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42641.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42642.cms',
 'https://economictimes.indiatimes.com/archivelist/year-2016,month-9,starttime-42643.cms']

In [5]:
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

for url in archive_url[1:5]:
    driver.get(url)
    news_link = driver.find_elements_by_xpath("//td[@class='contentbox5']//ul//li//a")
    urls = []
    for element in news_link:
        urls.append(element.get_attribute('href'))
    date = []
    author=[]
    vertical = []
    headline = []
    desc = []
    for i in urls:
        driver.get(i)

        current_url = driver.current_url
        
        try:
            date.append(driver.find_element_by_xpath("//time").text.replace('Updated: ','').replace('Created: ','').replace('Last ',''))
        except:
            date.append('-')
        try:
            
            desc.append(driver.find_element_by_xpath("//div[@class='artText medium'][1]").text.replace('\n',' '))
        except:
            desc.append('-')
        try:
            if driver.find_element_by_xpath("//div[@data-brcount='0']//p[1]").text[:2] == 'By':
                author.append(driver.find_element_by_xpath("//div[@data-brcount='0']//p[1]").text)
            else:
                author.append('ET Bureau')
        except:
            try:
                author.append(driver.find_element_by_xpath("//div[@class='dtc vam artByline']").text)
            except:
                author.append('-')
            
        try:
            headline.append(driver.find_element_by_xpath("//h1[@class='artTitle font_faus']").text)
        except:
            headline.append('-')
            
        if len(current_url.split('/')) == 8:
            vertical.append(current_url.split('/')[4])
        else:
            vertical.append(current_url.split('/')[3])

    df = pd.DataFrame()
    df_name = url.split('-')[3].replace('.cms','')
    df['Date'] = date
    df['Author'] = author
    df['Vertical'] = vertical
    df['Headline'] = headline
    df['Description'] = desc

In [10]:
df

,Date,Author,Vertical,Headline,Description
0,"Sep 20, 2016, 01:12 AM IST","PTILast Updated: Sep 20, 2016, 01:12 AM IST",politics-and-nation,Active support for terrorists like Hafiz Saeed...,GENEVA: India on Monday said it firmly believe...
1,"Sep 20, 2016, 11:29 AM IST","By Saloni Shukla, ET BureauLast Updated: Sep 2...",startups,"Paytm Payments Bank ties up with banks, MFS ah...",MUMBAI: Paytm payments bank has lined up a gam...
2,"Sep 20, 2016, 11:29 AM IST","By Saloni Shukla, ET BureauLast Updated: Sep 2...",personal-finance-news,"Paytm payments bank ties up with banks, mutual...",MUMBAI: Paytm payments bank has lined up a gam...
3,"Sep 20, 2016, 07:40 AM IST","By NIDHI SHARMA, ET BureauLast Updated: Sep 20...",politics-and-nation,Schemes for Dalit-run businesses no raging suc...,NEW DELHI: Fifty seven â€“ this is the number of...
4,"Sep 20, 2016, 12:05 PM IST","By Sanjay Singh, ET BureauLast Updated: Sep 20...",politics-and-nation,Keeping Akhileshâ€™s youth brigade in check may ...,NEW DELHI: SP Uttar Pradesh president Shivpal ...
...,...,...,...,...,...
346,"Sep 20, 2016, 11:15 PM IST","PTILast Updated: Sep 20, 2016, 11:15 PM IST",politics-and-nation,"China, India remain on path of 'remarkable gro...",UNITED NATIONS: US President Barack Obama toda...
347,"Sep 20, 2016, 11:23 PM IST","PTILast Updated: Sep 20, 2016, 11:23 PM IST",politics-and-nation,"AAP government will improve water, power, educ...",NEW DELHI: Delhi Deputy Chief Minister Manish ...
348,"Sep 20, 2016, 11:39 PM IST","PTILast Updated: Sep 20, 2016, 11:39 PM IST",commodities,Oil imports touch 7-yr high in August,NEW DELHI: India's crude oil imports touched 7...
349,"Sep 20, 2016, 11:53 PM IST","Last Updated: Sep 20, 2016, 11:53 PM IST",politics-and-nation,Women entitled to end pregnancy regardless of ...,"MUMBAI: Endorsing the right of a woman to ""lea..."
350,"Sep 20, 2016, 11:47 PM IST","PTILast Updated: Sep 20, 2016, 11:47 PM IST",politics-and-nation,Naveen Patnaik writes to Arun Jaitley on compe...,"BHUBANESWAR: Batting for states, Odisha Chief ..."

In [6]:
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

for url in archive_url[6:15]:
    driver.get(url)
    news_link = driver.find_elements_by_xpath("//td[@class='contentbox5']//ul//li//a")
    urls = []
    for element in news_link:
        urls.append(element.get_attribute('href'))
    date = []
    author=[]
    vertical = []
    headline = []
    desc = []
    for i in urls:
        driver.get(i)

        current_url = driver.current_url
        
        try:
            date.append(driver.find_element_by_xpath("//time").text.replace('Updated: ','').replace('Created: ','').replace('Last ',''))
        except:
            date.append('-')
        try:
            
            desc.append(driver.find_element_by_xpath("//div[@class='artText medium'][1]").text.replace('\n',' '))
        except:
            desc.append('-')
        try:
            if driver.find_element_by_xpath("//div[@data-brcount='0']//p[1]").text[:2] == 'By':
                author.append(driver.find_element_by_xpath("//div[@data-brcount='0']//p[1]").text)
            else:
                author.append('ET Bureau')
        except:
            try:
                author.append(driver.find_element_by_xpath("//div[@class='dtc vam artByline']").text)
            except:
                author.append('-')
            
        try:
            headline.append(driver.find_element_by_xpath("//h1[@class='artTitle font_faus']").text)
        except:
            headline.append('-')
            
        if len(current_url.split('/')) == 8:
            vertical.append(current_url.split('/')[4])
        else:
            vertical.append(current_url.split('/')[3])

    df = pd.DataFrame()
    df_name = url.split('-')[3].replace('.cms','')
    df['Date'] = date
    df['Author'] = author
    df['Vertical'] = vertical
    df['Headline'] = headline
    df['Description'] = desc

In [7]:
df

,Date,Author,Vertical,Headline,Description
0,"Sep 15, 2016, 11:50 AM IST","By Sarita C Singh, ET BureauLast Updated: Sep ...",industry,Prices of LED bulbs drop to Rs 38,NEW DELHI: Prices of LED bulbs being distribut...
1,"Sep 15, 2016, 12:05 AM IST","Last Updated: Sep 15, 2016, 12:05 AM IST",science,Two India-born MIT scientists win prestigious ...,"Washington/Bengaluru, Sep 15 (IANS) Two Indo-A..."
2,"Sep 15, 2016, 08:27 AM IST","By Rohini Singh, ET BureauLast Updated: Sep 15...",politics-and-nation,"Rift in Samajwadi Party gets wider, Amar Singh...",NEW DELHI: High drama and bitter feuding prece...
3,"Sep 15, 2016, 12:25 AM IST",ET Bureau,sports,"NFL-League fines Broncos' Stewart, Marshall fo...",Sept 14 (The Sports Xchange) - Denver Broncos ...
4,"Sep 15, 2016, 11:29 AM IST","By Arun Kumar, ET BureauLast Updated: Sep 15, ...",industry,Race to acquire two hotels of Leelaventure Ltd...,"NEW DELHI: Sovereign wealth funds, private equ..."
...,...,...,...,...,...
404,"Sep 15, 2016, 11:35 PM IST",ET Bureau,sports,Ice hockey-Profiles of teams competing in Worl...,Sept 15 (Reuters) - Brief profiles of the eigh...
405,"Sep 15, 2016, 11:35 PM IST",By Steve Keating,sports,PREVIEW-Ice hockey-Return of World Cup puts Ol...,"By Steve Keating TORONTO, Sept 15 (Reuters) - ..."
406,"Sep 15, 2016, 11:55 PM IST",ET Bureau,sports,Golf-European Tour Latest Italian Open leaderb...,Sept 15 (Gracenote) - Latest leaderboard in th...
407,"Sep 16, 2016, 11:51 AM IST","PTILast Updated: Sep 16, 2016, 11:51 AM IST",personal-finance-news,Petrol price up by 58 paise a litre; diesel cu...,NEW DELHI: Petrol price was today hiked by 58 ...
408,"Sep 16, 2016, 11:51 AM IST","PTILast Updated: Sep 16, 2016, 11:51 AM IST",industry,Petrol price up by 58 paise a litre; diesel cu...,NEW DELHI: Petrol price was today hiked by 58 ...

In [8]:
import os
import glob
import pandas as pd


extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
combined_csv = pd.concat([pd.read_csv(f,low_memory=False) for f in all_filenames ])

EmptyDataError: No columns to parse from file

NameError: name 'df' is not defined

In [9]:
df.to_csv('file1.csv')

In [11]:
df.shape

(409, 5)

In [ ]:
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

for url in archive_url[16:23]:
    driver.get(url)
    news_link = driver.find_elements_by_xpath("//td[@class='contentbox5']//ul//li//a")
    urls = []
    for element in news_link:
        urls.append(element.get_attribute('href'))
    date = []
    author=[]
    vertical = []
    headline = []
    desc = []
    for i in urls:
        driver.get(i)

        current_url = driver.current_url
        
        try:
            date.append(driver.find_element_by_xpath("//time").text.replace('Updated: ','').replace('Created: ','').replace('Last ',''))
        except:
            date.append('-')
        try:
            
            desc.append(driver.find_element_by_xpath("//div[@class='artText medium'][1]").text.replace('\n',' '))
        except:
            desc.append('-')
        try:
            if driver.find_element_by_xpath("//div[@data-brcount='0']//p[1]").text[:2] == 'By':
                author.append(driver.find_element_by_xpath("//div[@data-brcount='0']//p[1]").text)
            else:
                author.append('ET Bureau')
        except:
            try:
                author.append(driver.find_element_by_xpath("//div[@class='dtc vam artByline']").text)
            except:
                author.append('-')
            
        try:
            headline.append(driver.find_element_by_xpath("//h1[@class='artTitle font_faus']").text)
        except:
            headline.append('-')
            
        if len(current_url.split('/')) == 8:
            vertical.append(current_url.split('/')[4])
        else:
            vertical.append(current_url.split('/')[3])

    df = pd.DataFrame()
    df_name = url.split('-')[3].replace('.cms','')
    df['Date'] = date
    df['Author'] = author
    df['Vertical'] = vertical
    df['Headline'] = headline
    df['Description'] = desc

In [ ]:
df.to_csv('file2.csv')

In [ ]:
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

for url in archive_url[24:30]:
    driver.get(url)
    news_link = driver.find_elements_by_xpath("//td[@class='contentbox5']//ul//li//a")
    urls = []
    for element in news_link:
        urls.append(element.get_attribute('href'))
    date = []
    author=[]
    vertical = []
    headline = []
    desc = []
    for i in urls:
        driver.get(i)

        current_url = driver.current_url
        
        try:
            date.append(driver.find_element_by_xpath("//time").text.replace('Updated: ','').replace('Created: ','').replace('Last ',''))
        except:
            date.append('-')
        try:
            
            desc.append(driver.find_element_by_xpath("//div[@class='artText medium'][1]").text.replace('\n',' '))
        except:
            desc.append('-')
        try:
            if driver.find_element_by_xpath("//div[@data-brcount='0']//p[1]").text[:2] == 'By':
                author.append(driver.find_element_by_xpath("//div[@data-brcount='0']//p[1]").text)
            else:
                author.append('ET Bureau')
        except:
            try:
                author.append(driver.find_element_by_xpath("//div[@class='dtc vam artByline']").text)
            except:
                author.append('-')
            
        try:
            headline.append(driver.find_element_by_xpath("//h1[@class='artTitle font_faus']").text)
        except:
            headline.append('-')
            
        if len(current_url.split('/')) == 8:
            vertical.append(current_url.split('/')[4])
        else:
            vertical.append(current_url.split('/')[3])

    df = pd.DataFrame()
    df_name = url.split('-')[3].replace('.cms','')
    df['Date'] = date
    df['Author'] = author
    df['Vertical'] = vertical
    df['Headline'] = headline
    df['Description'] = desc

In [ ]:
df.to_csv('file3.csv')

In [ ]:
#adding the csv file into one 
#as the data was taking so much time to run so i made three ipynb file and run the code and now i will add the csv data in to one

In [1]:
import os
import glob
import pandas as pd
os.chdir(r"C:\Users\nehag")

In [2]:
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]

In [3]:
extension = 'csv'
all_filenames = [i for i in glob.glob('*.{}'.format(extension))]
combined_csv = pd.concat([pd.read_csv(f,low_memory=False) for f in all_filenames ])

In [4]:
combined_csv.head()

,Unnamed: 0,Date,Author,Vertical,Headline,Description
0,0,"Sep 15, 2016, 11:50 AM IST","By Sarita C Singh, ET BureauLast Updated: Sep ...",industry,Prices of LED bulbs drop to Rs 38,NEW DELHI: Prices of LED bulbs being distribut...
1,1,"Sep 15, 2016, 12:05 AM IST","Last Updated: Sep 15, 2016, 12:05 AM IST",science,Two India-born MIT scientists win prestigious ...,"Washington/Bengaluru, Sep 15 (IANS) Two Indo-A..."
2,2,"Sep 15, 2016, 08:27 AM IST","By Rohini Singh, ET BureauLast Updated: Sep 15...",politics-and-nation,"Rift in Samajwadi Party gets wider, Amar Singh...",NEW DELHI: High drama and bitter feuding prece...
3,3,"Sep 15, 2016, 12:25 AM IST",ET Bureau,sports,"NFL-League fines Broncos' Stewart, Marshall fo...",Sept 14 (The Sports Xchange) - Denver Broncos ...
4,4,"Sep 15, 2016, 11:29 AM IST","By Arun Kumar, ET BureauLast Updated: Sep 15, ...",industry,Race to acquire two hotels of Leelaventure Ltd...,"NEW DELHI: Sovereign wealth funds, private equ..."

In [5]:
combined_csv['Author'] = combined_csv.apply(lambda x: x['Author'].replace('Last Updated: ','').replace(x['Date'],'').replace('By ',''),axis=1)
combined_csv['Author'] = combined_csv.apply(lambda x: x['Author'].split(',')[0],axis=1)
combined_csv

,Unnamed: 0,Date,Author,Vertical,Headline,Description
0,0,"Sep 15, 2016, 11:50 AM IST",Sarita C Singh,industry,Prices of LED bulbs drop to Rs 38,NEW DELHI: Prices of LED bulbs being distribut...
1,1,"Sep 15, 2016, 12:05 AM IST",,science,Two India-born MIT scientists win prestigious ...,"Washington/Bengaluru, Sep 15 (IANS) Two Indo-A..."
2,2,"Sep 15, 2016, 08:27 AM IST",Rohini Singh,politics-and-nation,"Rift in Samajwadi Party gets wider, Amar Singh...",NEW DELHI: High drama and bitter feuding prece...
3,3,"Sep 15, 2016, 12:25 AM IST",ET Bureau,sports,"NFL-League fines Broncos' Stewart, Marshall fo...",Sept 14 (The Sports Xchange) - Denver Broncos ...
4,4,"Sep 15, 2016, 11:29 AM IST",Arun Kumar,industry,Race to acquire two hotels of Leelaventure Ltd...,"NEW DELHI: Sovereign wealth funds, private equ..."
...,...,...,...,...,...,...
382,382,"Sep 30, 2016, 11:25 PM IST",ET Bureau,sports,Soccer-Czech championship results and standings,Sept 30 (Gracenote) - Results and standings fr...
383,383,"Sep 30, 2016, 11:25 PM IST",ET Bureau,sports,Soccer-Croatian championship results and stand...,Sept 30 (Gracenote) - Results and standings fr...
384,384,"Sep 30, 2016, 11:27 PM IST",Rakhi Mazumdar,industry,Vedanta appoints Arun Kumar as new CFO,KOLKATA: Vedanta NSE 2.05 % Limited has announ...
385,385,"Sep 30, 2016, 11:30 PM IST",ET Bureau,sports,Soccer-Danish championship results and standings,Sept 30 (Gracenote) - Results and standings fr...
386,386,"Sep 30, 2016, 11:37 PM IST",PTI,news,"Petrol price hiked by 36 paise/litre, diesel c...",NEW DELHI: Petrol price was today hiked by 36 ...

In [6]:
combined_csv = combined_csv[combined_csv['Date'] != '-']
combined_csv.reset_index(inplace=True,drop=True)

In [7]:
combined_csv.to_csv(r'C:\Users\nehag\Documents\ET_Scraped_apr_2018.csv', index=False)

In [8]:
import pandas as pd
combined_csv = pd.read_csv(r'C:\Users\nehag\Documents\ET_Scraped_apr_2018.csv')

In [9]:
combined_csv.to_json(r'C:\Users\nehag\Documents\ET_Scraped_apr_2018.json',orient='index')

In [10]:
combined_csv.to_html(r'C:\Users\nehag\Documents\ET_Scraped_apr_2018.html',columns= combined_csv.columns)